=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/schemas/addOrderLine.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Sales order line detail",
  "type": "object",
  "properties": {
    "businessCreationDate": {
      "type": "string",
      "format": "date-time",
      "required": true
    },
    "creatorPerson": {
      "type": "object",
      "required": true,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "firstName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "familyName": {
          "type": "string",
          "maxLength": 80,
          "required": true
        }
      }
    },
    "customerProductReference": {
      "type": "string",
      "maxLength": 60,
      "required": false
    },
    "dropboxReplenishmentRequestRequested": {
      "type": "boolean",
      "required": false
    },
    "fixedPrice": {
      "type": "boolean",
      "required": false
    },
    "packaging": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "description": {
          "type": "string",
          "maxLength": 50,
          "required": true
        }
      }
    },
    "printedProductDescription": {
      "type": "string",
      "maxLength": 255,
      "required": false
    },
    "product": {
      "type": "object",
      "required": true,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "brandName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "color": {
          "type": "object",
          "required": false,
          "properties": {
            "ID": {
              "type": "string",
              "maxLength": 36,
              "required": true
            },
            "description": {
              "type": "string",
              "maxLength": 50,
              "required": true
            }
          }
        },
        "grade": {
          "type": "string",
          "maxLength": 50,
          "required": true
        },
        "producerColorCode": {
          "type": "string",
          "maxLength": 30,
          "required": false
        }
      }
    },
    "quantity": {
      "type": "object",
      "required": false,
      "properties": {
        "quantity": {
          "type": "number",
          "required": true
        },
        "unitCode": {
          "type": "string",
          "maxLength": 10,
          "required": true
        }
      }
    },
    "sample": {
      "type": "boolean",
      "required": false
    },
    "unitPrice": {
      "type": "object",
      "required": false,
      "properties": {
        "amount": {
          "type": "number",
          "required": true
        },
        "unitCode": {
          "type": "string",
          "maxLength": 10,
          "required": true
        }
      }
    }
  }
}

=== jmetzz/java-sandbox/json-transformation-lab/src/test/resources/sales/addOrderLine.json
{
  "businessCreationDate": "2016-01-02T12:22:50Z",
  "creatorPerson": {
    "creatorPersonID": "100",
    "firstName": "John",
    "familyName": "Doe"
  },
  "customerProductReference": "CUSTPROD",
  "fixedPrice": false,
  "packaging": {
    "packagingID": "74",
    "description": "plastic bag 25 kg"
  },
  "product": {
    "productID": "123",
    "brandName": "3M",
    "color": {
      "colorID": "123",
      "description": "BLACK"
    },
    "producerColorCode": "DARK"
  },
  "printedProductDescription": "This is my product description",
  "quantity": {
    "quantity": 750,
    "unitCode": "kg"
  },
  "sample": false,
  "unitPrice": {
    "amount": 1.25,
    "unitCode": "kg"
  }
}

=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/samples/addOrderLine.json
{
  "businessCreationDate": "2016-01-02T12:22:50Z",
  "creatorPerson": {
    "ID": "100",
    "firstName": "Frits",
    "familyName": "Spits"
  },
  "customerProductReference": "CUSTPROD",
  "dropboxReplenishmentRequestRequested": false,
  "fixedPrice": false,
  "packaging": {
    "ID": "74",
    "description": "plastic bag 25 kg"
  },
  "product": {
    "ID": "123",
    "brandName": "DOW",
    "color": {
      "ID": "123",
      "description": "BLACK"
    },
    "grade": "LDPE",
    "producerColorCode": "DARK"
  },
  "printedProductDescription": "This is my changed product description",
  "quantity": {
    "quantity": 750,
    "unitCode": "kg"
  },
  "sample": false,
  "unitPrice": {
    "amount": 1.25,
    "unitCode": "kg"
  }
}
