=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/schemas/createOrder.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Sales order details",
  "type": "object",
  "required": true,
  "properties": {
    "creatorPerson": {
      "type": "object",
      "required": true,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "firstName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "familyName": {
          "type": "string",
          "maxLength": 80,
          "required": true
        }
      }
    },
    "businessCreationDate": {
      "type": "string",
      "format": "date-time",
      "required": true
    },
    "transportType": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "description": {
          "type": "string",
          "maxLength": 50,
          "required": true
        }
      }
    },
    "currencyIsoCode": {
      "type": "string",
      "maxLength": 3,
      "minLength": 3,
      "required": false
    },
    "fuelSurcharge": {
      "type": "boolean",
      "required": true
    },
    "billingAddress": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "addressLine": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "addressName": {
          "type": "string",
          "maxLength": 255,
          "required": true
        },
        "cityName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "country": {
          "type": "object",
          "required": true,
          "properties": {
            "identificationCode": {
              "type": "string",
              "minLength": 2,
              "maxLength": 2,
              "required": true
            }
          }
        },
        "countrySubEntityCode": {
          "type": "string",
          "maxLength": 10,
          "required": false
        },
        "postalZone": {
          "type": "string",
          "maxLength": 20,
          "required": true
        }
      }
    },
    "customer": {
      "type": "object",
      "required": true,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        }
      }
    },
    "deliveryAddress": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "addressLine": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "addressName": {
          "type": "string",
          "maxLength": 255,
          "required": true
        },
        "cityName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "country": {
          "type": "object",
          "required": true,
          "properties": {
            "identificationCode": {
              "type": "string",
              "maxLength": 2,
              "minLength": 2,
              "required": true
            }
          }
        },
        "countrySubEntityCode": {
          "type": "string",
          "maxLength": 10,
          "required": false
        },
        "postalZone": {
          "type": "string",
          "maxLength": 20,
          "required": true
        }
      }
    },
    "deliveryInstructions": {
      "type": "string",
      "maxLength": 2000,
      "required": false
    },
    "paymentCondition": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "description": {
          "type": "string",
          "maxLength": 50,
          "required": true
        }
      }
    },
    "paymentDiscount": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "description": {
          "type": "string",
          "maxLength": 50,
          "required": true
        }
      }
    },
    "seller": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "firstName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "familyName": {
          "type": "string",
          "maxLength": 80,
          "required": true
        }
      }
    }
  }
}

=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/samples/createOrder.json
{
  "creatorPerson": {
    "ID": "100",
    "firstName": "Frits",
    "familyName": "Spits"
  },
  "businessCreationDate": "2015-07-26T12:25:57Z",
  "transportType": {
    "ID": "124",
    "description": "ROAD"
  },
  "currencyIsoCode": "EUR",
  "fuelSurcharge": true,
  "billingAddress": {
    "ID": "17831",
    "addressLine": "K Vypichu 1149",
    "addressName": "PORT BANGKOK",
    "cityName": "BANGKOK",
    "country": {
      "identificationCode": "THA"
    },
    "countrySubEntityCode": "BK",
    "postalZone": "THBKK"
  },
  "customer": {
    "ID": "12481",
    "callSign": "Loomans"
  },
  "deliveryAddress": {
    "ID": "583583",
    "addressLine": "Postbus 1350",
    "addressName": "BOEKELO DECOR",
    "cityName": "ENSCHEDE",
    "country": {
      "identificationCode": "NLD"
    },
    "countrySubEntityCode": "OVL",
    "postalZone": "7500 BJ"
  },
  "deliveryInstructions": "These are my delivery instructions",

"paymentCondition": {
    "ID": "10",
    "description": "30 days"
  },
  "paymentDiscount": {
    "ID": "21",
    "description": "5%"
  },
  "seller": {
    "ID": "201591",
    "firstName": "Peter",
    "familyName": "Seli"
  }
}

=== jmetzz/java-sandbox/json-transformation-lab/src/test/resources/sales/createOrder.json
{
  "creatorPerson": {
    "ID": "100",
    "firstName": "John",
    "familyName": "Doe"
  },
  "businessCreationDate": "2015-07-26T12:25:57Z",
  "transportType": {
    "ID": "124",
    "description": "ROAD"
  },
  "currencyIsoCode": "EUR",
  "fuelSurcharge": true,
  "billingAddress": {
    "ID": "17831",
    "addressLine": "Fireball street 689",
    "addressName": "Port Hoegaarden",
    "cityName": "Antwerp",
    "country": {
      "identificationCode": "BE"
    },
    "postalZone": "2100"
  },
  "customer": {
    "ID": "12481",
    "callSign": "Logan"
  },
  "deliveryAddress": {
    "ID": "583583",
    "addressLine": "Postbox 1350",
    "addressName": "RAIBOW DECOR",
    "cityName": "Breda",
    "country": {
      "identificationCode": "NL"
    },
    "postalZone": "7500 ZW"
  },
  "deliveryInstructions": "There are my delivery instructions",

  "paymentCondition": {
    "ID": "10",
    "description": "30 days"
  },
  "paymentDiscount": {
    "ID": "21",
    "description": "5%"
  },
  "seller": {
    "ID": "201591",
    "firstName": "Rui",
    "familyName": "Costa"
  }
}
