=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/schemas/getOrder.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Sales order details",
  "type": "object",
  "required": true,
  "properties": {
    "ID": {
      "type": "string",
      "maxLength": 36,
      "required": true
    },
    "automaticProformaInvoiceCommunication":{
      "type":"boolean",
      "required":true
    },
    "billingAddress": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "addressLine": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "addressName": {
          "type": "string",
          "maxLength": 255,
          "required": true
        },
        "cityName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "country": {
          "type": "object",
          "required": true,
          "properties": {
            "identificationCode": {
              "type": "string",
              "minLength": 2,
              "maxLength": 2,
              "required": true
            }
          }
        },
        "countrySubEntityCode": {
          "type": "string",
          "maxLength": 10,
          "required": false
        },
        "postalZone": {
          "type": "string",
          "maxLength": 20,
          "required": true
        }
      }
    },
    "billingContact": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "firstName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "familyName": {
          "type": "string",
          "maxLength": 80,
          "required": true
        }
      }
    },
    "businessCreationDate": {
      "type": "string",
      "format": "date-time",
      "required": true
    },
    "callOff": {
      "type": "boolean",
      "required": false
    },
    "confirmedDeliveryDate": {
      "type": "object",
      "required": false,
      "properties": {
        "from": {
          "type": "string",
          "format": "date",
          "required": true
        },
        "till": {
          "type": "string",
          "format": "date",
          "required": false
        },
        "isEditable": { 
          "type": "boolean", 
          "required": false 
        }         
      }
    },
    "creatorPerson": {
      "type": "object",
      "required": true,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "firstName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "familyName": {
          "type": "string",
          "maxLength": 80,
          "required": true
        }
      }
    },
    "currencyIsoCode": {
      "type": "string",
      "maxLength": 3,
      "minLength": 3,
      "required": false
    },
    "customer": {
      "type": "object",
      "required": true,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "callSign": {
          "type": "string",
          "maxLength": 60,
          "required": true
        }
      }
    },
    "customerOrderReference": {
      "type": "string",
      "maxLength": 40,
      "required": false
    },
    "deliveryInstructions": {
      "type": "string",
      "maxLength": 2000,
      "required": false
    },
    "deliveryTerm": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "description": {
          "type": "string",
          "maxLength": 50,
          "required": true
        }
      }
    },
    "deliveryTermAddress": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "addressLine": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "addressName": {
          "type": "string",
          "maxLength": 255,
          "required": true
        },
        "cityName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "country": {
          "type": "object",
          "required": true,
          "properties": {
            "identificationCode": {
              "type": "string",
              "minLength": 2,
              "maxLength": 2,
              "required": true
            }
          }
        },
        "countrySubEntityCode": {
          "type": "string",
          "maxLength": 10,
          "required": false
        },
        "postalZone": {
          "type": "string",
          "maxLength": 20,
          "required": true
        }
      }
    },
    "departureAddress": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "addressLine": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "addressName": {
          "type": "string",
          "maxLength": 255,
          "required": true
        },
        "cityName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "country": {
          "type": "object",
          "required": true,
          "properties": {
            "identificationCode": {
              "type": "string",
              "maxLength": 2,
              "minLength": 2,
              "required": true
            }
          }
        },
        "countrySubEntityCode": {
          "type": "string",
          "maxLength": 10,
          "required": false
        },
        "postalZone": {
          "type": "string",
          "maxLength": 20,
          "required": true
        }
      }
    },
    "destinationAddress": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "addressLine": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "addressName": {
          "type": "string",
          "maxLength": 255,
          "required": true
        },
        "cityName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "country": {
          "type": "object",
          "required": true,
          "properties": {
            "identificationCode": {
              "type": "string",
              "maxLength": 2,
              "minLength": 2,
              "required": true
            }
          }
        },
        "countrySubEntityCode": {
          "type": "string",
          "maxLength": 10,
          "required": false
        },
        "postalZone": {
          "type": "string",
          "maxLength": 20,
          "required": true
        }
      }
    },
    "fuelSurcharge": {
      "type": "boolean",
      "required": true
    },
    "internalComment": {
      "type": "string",
      "maxLength": 2000,
      "required": false
    },
    "locked": {
      "type":"boolean",
      "required": true
    },
    "loadDate": {
      "type": "string",
      "format": "date",
      "required": false
    },
    "loadDateIsEditable": { 
      "type": "boolean", 
      "required": false 
    },
    "loadingInstructions": {
      "type": "string",
      "maxLength": 2000,
      "required": false
    },
    "paymentCondition": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "description": {
          "type": "string",
          "maxLength": 40,
          "required": true
        }
      }
    },
    "paymentDiscount": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "description": {
          "type": "string",
          "maxLength": 50,
          "required": true
        }
      }
    },
    "entity": {
      "type": "object",
      "required": true,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "callSign": {
          "type": "string",
          "maxLength": 60,
          "required": true
        }
      }
    },
    "reactiveSalesPerson": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "firstName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "familyName": {
          "type": "string",
          "maxLength": 80,
          "required": true
        }
      }
    },
    "rejectionReason": {
      "type": "object",
      "required": false,
      "properties": {
        "rejectionReasonID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "rejectionReasonDesc": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "rejectionReasonComment": {
          "type": "string",
          "maxLength": 80,
          "required": false
        }
      }
    },
    "requestedDeliveryDate": {
      "type": "object",
      "required": false,
      "properties": {
        "from": {
          "type": "string",
          "format": "date",
          "required": true
        },
        "till": {
          "type": "string",
          "format": "date",
          "required": false
        }
      }
    },
    "requireManualAcceptance": {
      "type": "boolean",
      "required": true
    },
    "salesPerson": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "firstName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "familyName": {
          "type": "string",
          "maxLength": 80,
          "required": true
        }
      }
    },
    "status": {
      "type": "string",
      "maxLength": 50,
      "required": true
    },
    "systemCreationDate": {
      "type": "string",
      "format": "date-time",
      "required": true
    },
    "transportType": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "description": {
          "type": "string",
          "maxLength": 50,
          "required": true
        }
      }
    },
    "version": {
      "type": "integer",
      "required": true
    },
    "orderLines": {
      "type": "array",
      "required": false,
      "items": {
        "title": "Sales order line detail",
        "type": "object",
        "properties": {
          "orderID": {
            "type": "string",
            "maxLength": 36,
            "required": true
          },
          "ID": {
            "type": "string",
            "maxLength": 36,
            "required": true
          },
          "businessCreationDate": {
            "type": "string",
            "format": "date-time",
            "required": true
          },
          "customerProductReference": {
            "type": "string",
            "maxLength": 60,
            "required": false
          },
          "grossMarginTwo": {
            "type": "object",
            "required": false,
            "properties": {
              "value": {
                "type": "number",
                "required": true
              },
              "timestampOfCalculation": {
                "type": "string",
                "format": "date-time",
                "required": true
              }
            }
          },
          "packaging": {
            "type": "object",
            "required": false,
            "properties": {
              "ID": {
                "type": "string",
                "maxLength": 36,
                "required": true
              },
              "description": {
                "type": "string",
                "maxLength": 50,
                "required": true
              }
            }
          },
          "printedProductDescription": {
            "type": "string",
            "maxLength": 255,
            "required": false
          },
          "product": {
            "type": "object",
            "required": true,
            "properties": {
              "ID":{
                "type": "string",
                "maxLength": 36,
                "required": true
              },
              "brandName": {
                "type": "string",
                "maxLength": 40,
                "required": true
              },
              "color": {
                "type": "object",
                "required":true,
                "properties": {
                  "ID":{
                    "type": "string",
                    "maxLength": 36,
                    "required": true
                  },
                  "description": {
                    "type": "string",
                    "maxLength": 50,
                    "required": true
                  }
                }
              },
              "grade": {
                "type": "string",
                "maxLength": 50,
                "required": true
              },
              "producerColorCode": {
                "type": "string",
                "maxLength": 30,
                "required": false
              }
            }
          },
          "quantityRavagoEntity": {
            "type": "object",
            "required": false,
            "properties": {
              "quantity": {
                "type": "number",
                "required": true
              },
              "unitCode": {
                "type": "string",
                "maxLength": 10,
                "required": true
              }
            }
          },
          "quantityCustomer": {
            "type": "object",
            "required": false,
            "properties": {
              "quantity": {
                "type": "number",
                "required": true
              },
              "unitCode": {
                "type": "string",
                "maxLength": 10,
                "required": true
              }
            }
          },
          "stateChecks": {
            "type": "array",
            "required": false,
            "items": {
              "type": "object",
              "required": true,
              "properties": {
                "check": {
                  "type": "string",
                  "required": true,
                  "maxLength": 50
                },
                "value": {
                  "type": "string",
                  "required": true,
                  "maxLength": 50
                }
              }
            }
          },
          "status": {
            "type": "string",
            "maxLength": 50,
            "required": true
          },
          "unitPriceCustomer": {
            "type": "object",
            "required": false,
            "properties": {
              "amount": {
                "type": "number",
                "required": true
              },
              "unitCode": {
                "type": "string",
                "maxLength": 10,
                "required": true
              }
            }
          },
          "unitPriceRavagoEntity": {
            "type": "object",
            "required": false,
            "properties": {
              "amount": {
                "type": "number",
                "required": true
              },
              "unitCode": {
                "type": "string",
                "maxLength": 10,
                "required": true
              }
            }
          },
          "version": {
            "type": "integer",
            "required": true
          }
        }
      }
    }
  }
}

=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/samples/getOrder.json
{
  "ID": "SALES123",
  "automaticProformaInvoiceCommunication": false,
  "billingAddress": {
    "ID": "17831",
    "addressLine": "K Vypichu 1149",
    "addressName": "PORT BANGKOK",
    "cityName": "BANGKOK",
    "country": {
      "identificationCode": "TH"
    },
    "countrySubEntityCode": "BK",
    "postalZone": "THBKK"
  },
  "billingContact": {
    "ID": "123456",
    "firstName": "Jos",
    "familyName": "Smos"
  },
  "businessCreationDate": "2015-07-26T10:22:51Z",
  "callOff": false,
  "confirmedDeliveryDate": {
    "from": "2016-02-11",
    "till": "2016-02-15",
    "isEditable":true
  },
  "creatorPerson": {
    "ID": "100",
    "firstName": "Frits",
    "familyName": "Spits"
  },
  "currencyIsoCode": "EUR",
  "customer": {
    "ID": "12481",
    "callSign": "Loomans"
  },
  "customerOrderReference": "SALES4875",
  "deliveryInstructions": "These are my delivery instructions",
  "deliveryTerm": {
    "ID": "10",
    "description": "EXW"
  },
  "deliveryTermAddress": {
    "ID": "17831",
    "addressLine": "K Vypichu 1149",
    "addressName": "PORT BANGKOK",
    "cityName": "BANGKOK",
    "country": {
      "identificationCode": "TH"
    },
    "countrySubEntityCode": "BK",
    "postalZone": "THBKK"
  },
  "departureAddress": {
    "ID": "564972",
    "addressLine": "Zeelsebaan 24",
    "addressName": "MOENS VERPAKKINGEN",
    "cityName": "DENDERMONDE",
    "country": {
      "identificationCode": "BE"
    },
    "countrySubEntityCode": "OV",
    "postalZone": "9200"
  },
  "destinationAddress": {
    "ID": "583583",
    "addressLine": "Postbus 1350",
    "addressName": "BOEKELO DECOR",
    "cityName": "ENSCHEDE",
    "country": {
      "identificationCode": "NL"
    },
    "countrySubEntityCode": "OVL",
    "postalZone": "7500 BJ"
  },
  "fuelSurcharge": true,
  "internalComment": "This is my internal comment",
  "locked": true,
  "loadDate": "2016-02-07",
  "loadDateIsEditable":true,
  "loadingInstructions": "These are my loading instructions",
  "paymentCondition": {
    "ID": "10",
    "description": "30 days"
  },
  "paymentDiscount": {
    "ID": "21",
    "description": "5%"
  },
  "entity": {
    "ID": "124",
    "callSign": "Company Distribution"
  },
  "reactiveSalesPerson": {
    "ID": "71948",
    "firstName": "Tom",
    "familyName": "Aat"
  },
  "rejectionReason": {
    "rejectionReasonID": "12345",
    "rejectionReasonDesc": "Wrong Data",
    "rejectionReasonComment": "This order was rejected because the wrong sales person was entered"
  },
  "requestedDeliveryDate": {
    "from": "2016-01-15",
    "till": "2016-02-29"
  },
  "requireManualAcceptance": true,
  "salesPerson": {
    "ID": "201591",
    "firstName": "Peter",
    "familyName": "Seli"
  },
  "status": "Rejected",
  "systemCreationDate": "2016-01-07T10:22:57Z",
  "transportType": {
    "ID": "124",
    "description": "ROAD"
  },
  "version": 1,
  "orderLines": [
    {
      "orderID": "SALES123",
      "ID": "SALESLINE12156",
      "businessCreationDate": "2016-01-02T10:22:50Z",
      "customerProductReference": "CUSTPROD",
      "packaging": {
        "ID": "74",
        "description": "plastic bag 25 kg"
      },
      "grossMarginTwo": {
        "value": 22,
        "timestampOfCalculation": "2016-02-17T17:22:35Z"
      },
      "printedProductDescription": "This is the product description that will be printed",
      "product": {
        "ID": "123",
        "brandName": "DOW",
        "color": {
          "ID": "123",
          "description": "BLACK"
        },
        "grade": "LDPE",
        "producerColorCode": "DARK"
      },
      "quantityRavagoEntity": {
        "quantity": 750,
        "unitCode": "kg"
      },
      "quantityCustomer": {
        "quantity": 1653.46,
        "unitCode": "lb"
      },
      "stateChecks": [
        {
          "check": "AVAILABILITY",
          "value": "NOT_ASSIGNED"
        },
        {
          "check": "COMMERCIAL_VIABILITY",
          "value": "APPROVED"
        },
        {
          "check": "CREDIT",
          "value": "NOT_ASSIGNED"
        }
      ],
      "status": "Accepted",
      "unitPriceCustomer": {
        "amount": 1.25,
        "unitCode": "kg"
      },
      "unitPriceRavagoEntity": {
        "amount": 0.5669,
        "unitCode": "lb"
      },
      "version": 1
    }
  ]
}
