=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/schemas/getOrderLines.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "List of sales order lines",
  "type": "array",
  "items": {
    "title": "Sales order line detail",
    "type": "object",
    "properties": {
      "orderID": {
        "type": "string",
        "maxLength": 36,
        "required": true
      },
      "ID": {
        "type": "string",
        "maxLength": 36,
        "required": true
      },
      "businessCreationDate": {
        "type": "string",
        "format": "date-time",
        "required": true
      },
      "customerProductReference": {
        "type": "string",
        "maxLength": 60,
        "required": false
      },
      "directDelivery": {
        "type": "boolean",
        "required": false
      },
      "grossMarginTwo": {
        "type": "object",
        "required": false,
        "properties": {
          "value": {
            "type": "number",
            "required": true
          },
          "timestampOfCalculation": {
            "type": "string",
            "format": "date-time",
            "required": true
          }
        }
      },
      "packaging": {
        "type": "object",
        "required": false,
        "properties": {
          "ID": {
            "type": "string",
            "maxLength": 36,
            "required": true
          },
          "description": {
            "type": "string",
            "maxLength": 50,
            "required": true
          }
        }
      },
      "printedProductDescription": {
        "type": "string",
        "maxLength": 255,
        "required": false
      },
      "product": {
        "type": "object",
        "required": true,
        "properties": {
          "ID": {
            "type": "string",
            "maxLength": 36,
            "required": true
          },
          "brandName": {
            "type": "string",
            "maxLength": 40,
            "required": true
          },
          "color": {
            "type": "object",
            "required": false,
            "properties": {
              "ID": {
                "type": "string",
                "maxLength": 36,
                "required": true
              },
              "description": {
                "type": "string",
                "maxLength": 50,
                "required": true
              }
            }
          },
          "grade": {
            "type": "string",
            "maxLength": 50,
            "required": true
          },
          "producerColorCode": {
            "type": "string",
            "maxLength": 30,
            "required": false
          }
        }
      },
      "quantity": {
        "type": "object",
        "required": false,
        "properties": {
          "quantity": {
            "type": "number",
            "required": true
          },
          "unitCode": {
            "type": "string",
            "maxLength": 10,
            "required": true
          },
          "isEditable": { 
            "type": "boolean", 
            "required": false 
          }         
        }
      },
      "stateChecks": {
        "type": "array",
        "required": false,
        "items": {
          "type": "object",
          "required": true,
          "properties": {
            "check": {
              "type": "string",
              "required": true,
              "maxLength": 50
            },
            "value": {
              "type": "string",
              "required": true,
              "maxLength": 50
            }
          }
        }
      },
      "status": {
        "type": "string",
        "maxLength": 50,
        "required": true
      },
      "unitPrice": {
        "type": "object",
        "required": false,
        "properties": {
          "amount": {
            "type": "number",
            "required": true
          },
          "unitCode": {
            "type": "string",
            "maxLength": 10,
            "required": true
          }
        }
      },
      "version": {
        "type": "integer",
        "required": true
      }
    }
  }
}

=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/samples/getOrderLines.json
[
  {
    "orderID": "SALES123",
    "ID":"SALESLINE12156",
    "businessCreationDate": "2016-01-02T10:22:50Z",
    "customerProductReference": "CUSTPROD",
    "directDelivery": false,
    "grossMarginTwo": {
      "value": 22,
      "timestampOfCalculation": "2016-02-17T17:22:35Z"
    },
    "packaging": {
      "ID": "74",
      "description": "plastic bag 25 kg"
    },
    "printedProductDescription": "This is the product description that will be printed",
    "product": {
      "ID": "123",
      "brandName": "DOW",
      "color": {
        "ID": "123",
        "description": "BLACK"
      },
      "grade": "LDPE",
      "producerColorCode": "DARK"
    },
    "quantity": {
      "quantity": 750,
      "unitCode": "kg",
      "isEditable":true
    },
    "stateChecks": [
      {
        "check": "AVAILABILITY",
        "value": "NOT_ASSIGNED"
      },
      {
        "check": "COMMERCIAL_VIABILITY",
        "value": "APPROVED"
      },
      {
        "check": "CREDIT",
        "value": "NOT_ASSIGNED"
      }
    ],
    "status": "Accepted",
    "unitPrice": {
      "amount": 1.25,
      "unitCode": "kg"
    },
    "version": 1
  }
]
