=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/schemas/modifyOrderLine.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Sales order line detail",
  "type": "object",
  "properties": {
    "customerProductReference": {
      "type": "string",
      "maxLength": 60,
      "required": false
    },
    "fixedPrice": {
      "type": "boolean",
      "required": false
    },
    "grossMarginTwo":{
      "type": "object",
      "required": false,
      "properties": {
        "value":{
          "type":"number",
          "required":true
        },
        "timestampOfCalculation": {
          "type":"string",
          "format": "date-time",
          "required": true
        }
      }
    },
    "packaging": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "description": {
          "type": "string",
          "maxLength": 50,
          "required": true
        }
      }
    },
    "printedProductDescription": {
      "type": "string",
      "maxLength": 255,
      "required": false
    },
    "product": {
      "type": "object",
      "required": true,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "brandName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "color": {
          "type": "object",
          "required": false,
          "properties": {
            "ID": {
              "type": "string",
              "maxLength": 36,
              "required": true
            },
            "description": {
              "type": "string",
              "maxLength": 50,
              "required": true
            }
          }
        },
        "grade": {
          "type": "string",
          "maxLength": 50,
          "required": true
        },
        "producerColorCode": {
          "type": "string",
          "maxLength": 30,
          "required": false
        }
      }
    },
    "quantity": {
      "type": "object",
      "required": false,
      "properties": {
        "quantity": {
          "type": "number",
          "required": true
        },
        "unitCode": {
          "type": "string",
          "maxLength": 10,
          "required": true
        }
      }
    },
    "sample": {
      "type": "boolean",
      "required": false
    },
    "unitPrice": {
      "type": "object",
      "required": false,
      "properties": {
        "amount": {
          "type": "number",
          "required": true
        },
        "unitCode": {
          "type": "string",
          "maxLength": 10,
          "required": true
        }
      }
    },
    "version": {
      "type": "number",
      "required": true
    }
  }
}

=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/samples/modifyOrderLine.json
{
  "customerProductReference": "CUSTPROD",
  "fixedPrice": false,
  "grossMarginTwo": {
    "value": 22,
    "timestampOfCalculation": "2016-02-17T17:22:35Z"
  },
  "packaging": {
    "ID": "74",
    "description": "plastic bag 25 kg"
  },
  "printedProductDescription": "This is my changed product description",
  "product": {
    "ID": "123",
    "brandName": "DOW",
    "color": {
      "ID": "123",
      "description": "BLACK"
    },
    "grade": "LDPE",
    "producerColorCode": "DARK"
  },
  "quantity": {
    "quantity": 750,
    "unitCode": "kg"
  },
  "sample": false,
  "unitPrice": {
    "amount": 1.25,
    "unitCode": "kg"
  },
  "version": 1
}
