=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/schemas/modifyOrder.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Sales order details",
  "type": "object",
  "required": true,
  "properties": {
    "automaticProformaInvoiceCommunication":{
      "type":"boolean",
      "required":false
    },
    "billingAddress": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "addressLine": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "addressName": {
          "type": "string",
          "maxLength": 255,
          "required": true
        },
        "cityName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "country": {
          "type": "object",
          "required": true,
          "properties": {
            "identificationCode": {
              "type": "string",
              "minLength": 2,
              "maxLength": 2,
              "required": true
            }
          }
        },
        "countrySubEntityCode": {
          "type": "string",
          "maxLength": 10,
          "required": false
        },
        "postalZone": {
          "type": "string",
          "maxLength": 20,
          "required": true
        }
      }
    },
    "billingContact": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "firstName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "familyName": {
          "type": "string",
          "maxLength": 80,
          "required": true
        }
      }
    },
    "callOff": {
      "type": "boolean",
      "required": false
    },
    "confirmedDeliveryDate": {
      "type": "object",
      "required": false,
      "properties": {
        "from": {
          "type": "string",
          "format": "date",
          "required": true
        },
        "till": {
          "type": "string",
          "format": "date",
          "required": false
        }
      }
    },
    "customer": {
      "type": "object",
      "required": true,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "callSign": {
          "type": "string",
          "maxLength": 60,
          "required": true
        }
      }
    },
    "customerOrderReference": {
      "type": "string",
      "maxLength": 40,
      "required": false
    },
    "deliveryInstructions": {
      "type": "string",
      "maxLength": 2000,
      "required": false
    },
    "deliveryTerm": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "description": {
          "type": "string",
          "maxLength": 50,
          "required": true
        }
      }
    },
    "destinationAddress": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "addressLine": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "addressName": {
          "type": "string",
          "maxLength": 255,
          "required": true
        },
        "cityName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "country": {
          "type": "object",
          "required": true,
          "properties": {
            "identificationCode": {
              "type": "string",
              "maxLength": 2,
              "minLength": 2,
              "required": true
            }
          }
        },
        "countrySubEntityCode": {
          "type": "string",
          "maxLength": 10,
          "required": false
        },
        "postalZone": {
          "type": "string",
          "maxLength": 20,
          "required": true
        }
      }
    },
    "fuelSurcharge": {
      "type": "boolean",
      "required": true
    },
    "internalComment": {
      "type": "string",
      "maxLength": 2000,
      "required": false
    },
    "loadDate": {
      "type": "string",
      "format": "date",
      "required": false
    },
    "loadingInstructions": {
      "type": "string",
      "maxLength": 2000,
      "required": false
    },
    "entity": {
      "type": "object",
      "required": true,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "callSign": {
          "type": "string",
          "maxLength": 60,
          "required": true
        }
      }
    },
    "reactiveSalesPerson": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "firstName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "familyName": {
          "type": "string",
          "maxLength": 80,
          "required": true
        }
      }
    },
    "requestedDeliveryDate": {
      "type": "object",
      "required": false,
      "properties": {
        "from": {
          "type": "string",
          "format": "date",
          "required": true
        },
        "till": {
          "type": "string",
          "format": "date",
          "required": false
        }
      }
    },
    "requireManualAcceptance": {
      "type": "boolean",
      "required": true
    },
    "salesPerson": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "firstName": {
          "type": "string",
          "maxLength": 40,
          "required": true
        },
        "familyName": {
          "type": "string",
          "maxLength": 80,
          "required": true
        }
      }
    },
    "transportType": {
      "type": "object",
      "required": false,
      "properties": {
        "ID": {
          "type": "string",
          "maxLength": 36,
          "required": true
        },
        "description": {
          "type": "string",
          "maxLength": 50,
          "required": true
        }
      }
    },
    "version": {
      "type": "integer",
      "required": true
    }
  }
}

=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/samples/modifyOrder.json
{
  "automaticProformaInvoiceCommunication": false,
  "billingAddress": {
    "ID": "17831",
    "addressLine": "K Vypichu 1149",
    "addressName": "PORT BANGKOK",
    "cityName": "BANGKOK",
    "country": {
      "identificationCode": "TH"
    },
    "countrySubEntityCode": "BK",
    "postalZone": "THBKK"
  },
  "billingContact": {
    "ID": "123456",
    "firstName": "Jos",
    "familyName": "Smos"
  },
  "callOff": false,
  "confirmedDeliveryDate": {
    "from": "2016-02-11",
    "till": "2016-02-15"
  },
  "customer": {
    "ID": "12481",
    "callSign": "Loomans"
  },
  "customerOrderReference": "SALES4875",
  "deliveryInstructions": "These are my delivery instructions",
  "deliveryTerm": {
    "ID": "10",
    "description": "EXW"
  },
  "destinationAddress": {
    "ID": "583583",
    "addressLine": "Postbus 1350",
    "addressName": "BOEKELO DECOR",
    "cityName": "ENSCHEDE",
    "country": {
      "identificationCode": "NL"
    },
    "countrySubEntityCode": "OVL",
    "postalZone": "7500 BJ"
  },
  "fuelSurcharge": true,
  "internalComment": "This is my internal comment",
  "loadDate": "2016-02-07",
  "loadingInstructions": "These are my loading instructions",
  "entity": {
    "ID": "124",
    "callSign": "Company Distribution"
  },
  "reactiveSalesPerson": {
    "ID": "71948",
    "firstName": "Tom",
    "familyName": "Aat"
  },
  "requestedDeliveryDate": {
    "from": "2016-01-15",
    "till": "2016-02-29"
  },
  "requireManualAcceptance": false,
  "salesPerson": {
    "ID": "201591",
    "firstName": "Peter",
    "familyName": "Seli"
  },
  "transportType": {
    "ID": "124",
    "description": "ROAD"
  },
  "version": 1
}
