=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/schemas/searchOrders.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "List of sales orders",
  "type": "array",
  "items": {
    "title": "Sales order details",
    "type": "object",
    "properties": {
      "ID": {
        "type": "string",
        "maxLength":36,
        "required": true
      },
      "businessCreationDate": {
        "type": "string",
        "format": "date-time",
        "required": true
      },
      "callOff": {
        "type": "boolean",
        "required": false
      },
      "confirmedDeliveryDate": {
        "type": "object",
        "required": false,
        "properties": {
          "from": {
            "type": "string",
            "format": "date",
            "required": true
          },
          "till": {
            "type": "string",
            "format": "date",
            "required": false
          }
        }
      },
      "creatorPerson": {
        "type": "object",
        "required": true,
        "properties": {
          "ID": {
            "type": "string",
            "maxLength":36,
            "required": true
          },
          "firstName": {
            "type": "string",
            "maxLength": 40,
            "required": true
          },
          "familyName": {
            "type": "string",
            "maxLength": 80,
            "required": true
          }
        }
      },
      "customer": {
        "type": "object",
        "required": true,
        "properties": {
          "ID": {
            "type": "string",
            "maxLength": 36,
            "required": true
          },
          "callSign": {
            "type": "string",
            "maxLength": 60,
            "required": true
          }
        }
      },
      "customerOrderReference": {
        "type": "string",
        "maxLength": 40,
        "required": false
      },
      "fuelSurcharge": {
        "type": "boolean",
        "required": true
      },
      "internalComment": {
        "type": "string",
        "maxLength": 2000,
        "required": false
      },
      "entity": {
        "type": "object",
        "required": true,
        "properties": {
          "ID": {
            "type": "string",
            "maxLength": 36,
            "required": true
          },
          "callSign": {
            "type": "string",
            "maxLength": 60,
            "required": true
          }
        }
      },
      "reactiveSalesPerson": {
        "type": "object",
        "required": true,
        "properties": {
          "ID": {
            "type": "string",
            "maxLength": 36,
            "required": true
          },
          "firstName": {
            "type": "string",
            "maxLength": 40,
            "required": true
          },
          "familyName": {
            "type": "string",
            "maxLength": 80,
            "required": true
          }
        }
      },
      "rejectionReason": {
        "type": "object",
        "required": false,
        "properties": {
          "ID": {
            "type": "string",
            "maxLength": 36,
            "required": true
          },
          "description": {
            "type": "string",
            "maxLength": 40,
            "required": true
          },
          "comment": {
            "type": "string",
            "maxLength": 80,
            "required": false
          }
        }
      },
      "requestedDeliveryDate": {
        "type": "object",
        "required": false,
        "properties": {
          "from": {
            "type": "string",
            "format": "date",
            "required": true
          },
          "till": {
            "type": "string",
            "format": "date",
            "required": false
          }
        }
      },
      "salesPerson": {
        "type": "object",
        "required": true,
        "properties": {
          "ID": {
            "type": "string",
            "maxLength": 36,
            "required": true
          },
          "firstName": {
            "type": "string",
            "maxLength": 40,
            "required": true
          },
          "familyName": {
            "type": "string",
            "maxLength": 80,
            "required": true
          }
        }
      },
      "status": {
        "type": "string",
        "maxLength": 50,
        "required": true
      },
      "systemCreationDate": {
        "type": "string",
        "format": "date-time",
        "required": true
      },
      "version": {
        "type": "integer",
        "required": true
      }
    }
  }
}

=== jmetzz/java-sandbox/json-transformation-lab/src/main/resources/api/samples/searchOrders.json
[
  {
    "ID":"SALES123",
    "businessCreationDate":"2015-07-26T15:42:16Z",
    "callOff":false,
    "confirmedDeliveryDate":{
      "from":"2016-02-11",
      "till":"2016-02-15"
    },
    "creatorPerson":{
      "ID":"100",
      "firstName":"Frits",
      "familyName":"Spits"
    },
    "customer":{
      "ID":"12481",
      "callSign":"Loomans"
    },
    "customerOrderReference":"SALES4875",
    "fuelSurcharge": true,
    "internalComment":"This is my internal comment",
    "entity":{
      "ID":"124",
      "callSign":"Company Distribution"
    },
    "reactiveSalesPerson":{
      "ID":"71948",
      "firstName":"Tom",
      "familyName":"Aat"
    },
    "rejectionReason": {
      "ID":"12345",
      "description": "Wrong Data",
      "comment":"This order was rejected because the wrong sales person was entered"
    },
    "requestedDeliveryDate":{
      "from":"2016-01-15",
      "till":"2016-02-29"
    },
    "salesPerson":{
      "ID":"201591",
      "firstName":"Peter",
      "familyName":"Seli"
    },
    "status":"Rejected",
    "systemCreationDate":"2016-01-07T10:22:57Z",
    "version":1
  }
]
